

language: python
python:
  - "2.7"

# command to install dependencies
install:
  - echo "Installation of the repository"
  - pip install .
  - pip install python-coveralls  # Add me to install python-coveralls
# command to run tests
script:
  - echo "Launch general integrity test"
  - axondeepseg_test
  - py.test . -v --cov . --cov-report term-missing
after_success:
  - coveralls
